"Atributo (Back-end)","Tipo (Back-end)","Atributo (Front-end)","Tipo (Front-end)","Observações / Correções Sugeridas","Status"
"id","Long","id","string","OK: Exibição no front como string.","Consistente"
"code","String (único)","-","-","Faltando no Front: Adicionar campo 'code' nos formulários quando usar POST /api/fields/. Se usar /api/fields/from-file/, o back define code = fieldName e acrescenta sufixo.","Crítico"
"fieldName","String","name","string","Mapear name (front) → fieldName (back).","Requer Mapeamento"
"totalAreaHec","Float","area","string","Mapear area → totalAreaHec e converter para float (>0). Regex e refine já existem no schema do front.","Requer Mapeamento"
"farmId","Long","- (contexto Propriety)","number","Faltando no Front nos forms: Enviar farmId numérico. Em /from-file/ é @RequestParam; em /api/fields/ vai no corpo.","Crítico"
"coordinates","List<CoordinateDto {latitude,longitude}>","coordinatesFile","File | null","Divergente: Front usa GeoJSON via coordinatesFile. Usar POST /api/fields/from-file/ com farmId. Se usar /api/fields/, parsear GeoJSON e enviar coordinates[].","Requer Mapeamento"
"farmName (resposta)","String","-","-","Opcional exibir no front (somente leitura).","Apenas Leitura"
"analyses (relação)","List<Analysis>","-","-","Não trafega no FieldResponse padrão; usar endpoints de análises por talhão quando necessário.","Não Aplicável"
"crop","-","crop","string","Inexistente no back: Campo do front para exibição/negócio. Avaliar destino (outra entidade/analysis).","Front-only"
"precedingCrop","-","precedingCrop","string","Inexistente no back. Mesmo tratamento de 'crop'.","Front-only"
"harvest","-","harvest","string","Inexistente no back. Mesmo tratamento de 'crop'.","Front-only"
"description","-","description","string","Inexistente no back. Apenas exibição/nota no front.","Front-only"
"color","-","color","string","Inexistente no back. Apenas exibição visual no front.","Front-only"
"enrollmentDate","-","enrollmentDate","string","Inexistente no back (Field não possui createdAt/updatedAt). Apenas exibição no front.","Front-only"
